name = "liora-production-app"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "liora-app"
database_id = "fd7668f3-8822-4bfe-a219-eecaebc3adb8"
migrations_dir = "./drizzle"
